name:"hola mundo"

on:
  push:
    branches: ["master"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
       uses: actions/checkout@v4
       -run: echo "Hacemos pull del codigo"    
       -run: echo "correr migraciones"
       -run: echo "Generar binario"
       -run: "Publicar version"