name: "hola mundo"

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
       
       - run: echo "Hacemos pull del codigo"    
       - run: echo "correr migraciones"
       - run: echo "Generar binario"
       - run: echo  "Publicar version"